import type { RegistryItem } from "./types";

export const toolkits: RegistryItem[] = [
  {
    name: "github",
    type: "registry:toolkit",
    title: "GitHub",
    description: "GitHub connector via GitHub Copilot MCP",
    icon: "https://registry.kernl.sh/icons/github.svg",
    category: "developer-tools",
    env: ["GITHUB_TOKEN"],
    files: [{ path: "toolkits/github/index.ts" }],
  },
  {
    name: "linear",
    type: "registry:toolkit",
    title: "Linear",
    description: "Linear issue tracking and project management",
    icon: "https://registry.kernl.sh/icons/linear.svg",
    category: "project-management",
    env: ["LINEAR_API_KEY"],
    files: [{ path: "toolkits/linear/index.ts" }],
  },
  {
    name: "exa",
    type: "registry:toolkit",
    title: "Exa",
    description: "Real-time web search and code context via Exa AI",
    icon: "https://registry.kernl.sh/icons/exa.svg",
    category: "search",
    env: ["EXA_API_KEY"],
    files: [{ path: "toolkits/exa/index.ts" }],
  },
  {
    name: "parallel",
    type: "registry:toolkit",
    title: "Parallel",
    description: "Real-time web search and content extraction via Parallel AI",
    icon: "https://registry.kernl.sh/icons/parallel.svg",
    category: "search",
    env: ["PARALLEL_API_KEY"],
    files: [{ path: "toolkits/parallel/index.ts" }],
  },
  {
    name: "alai",
    type: "registry:toolkit",
    title: "Alai",
    description: "Transform text content into fully designed presentations",
    icon: "https://registry.kernl.sh/icons/alai.svg",
    category: "productivity",
    env: ["ALAI_API_KEY"],
    files: [
      { path: "toolkits/alai/index.ts" },
      { path: "toolkits/alai/client.ts" },
    ],
  },
  {
    name: "agentmail",
    type: "registry:toolkit",
    title: "AgentMail",
    description: "Email API for AI agents - send, receive, and manage emails",
    icon: "https://registry.kernl.sh/icons/agentmail.svg",
    category: "communication",
    dependencies: ["agentmail@^0.1.13"],
    env: ["AGENTMAIL_API_KEY", "AGENTMAIL_INBOX_ID"],
    files: [
      { path: "toolkits/agentmail/index.ts" },
      { path: "toolkits/agentmail/client.ts" },
      { path: "toolkits/agentmail/messages.ts" },
      { path: "toolkits/agentmail/threads.ts" },
      { path: "toolkits/agentmail/drafts.ts" },
    ],
  },
  {
    name: "daytona",
    type: "registry:toolkit",
    title: "Daytona",
    description: "Cloud sandbox for code execution, file system, git, and desktop automation",
    icon: "https://registry.kernl.sh/icons/daytona.svg",
    category: "developer-tools",
    dependencies: ["@daytonaio/sdk@^0.128.1"],
    env: ["DAYTONA_API_KEY"],
    files: [
      { path: "toolkits/daytona/index.ts" },
      { path: "toolkits/daytona/client.ts" },
      { path: "toolkits/daytona/code.ts" },
      { path: "toolkits/daytona/computer.ts" },
      { path: "toolkits/daytona/fs.ts" },
      { path: "toolkits/daytona/git.ts" },
      { path: "toolkits/daytona/process.ts" },
    ],
  },
  {
    name: "turbopuffer",
    type: "registry:toolkit",
    title: "turbopuffer",
    description: "Vector database for semantic search and retrieval",
    icon: "https://registry.kernl.sh/icons/turbopuffer.svg",
    category: "search",
    dependencies: ["@kernl-sdk/turbopuffer@^0.1.6"],
    env: ["TURBOPUFFER_API_KEY", "TURBOPUFFER_REGION"],
    files: [
      { path: "toolkits/turbopuffer/index.ts" },
      { path: "toolkits/turbopuffer/client.ts" },
      { path: "toolkits/turbopuffer/search.ts" },
      { path: "toolkits/turbopuffer/upsert.ts" },
    ],
  },
];
