packages:
  - packages/*
  - packages/providers/*
  - packages/storage/*
  - packages/observability/*
  - microprojects/playground/*
  - microprojects/docster
  - apps/*
  - apps/popcorn/*

catalog:
  "@kobalte/core": ^0.13.11
  "@pierre/diffs": ^1.0.4
  "@solid-primitives/storage": ^4.3.3
  "@solidjs/meta": ^0.29.4
  "@solidjs/router": ^0.15.4
  "@tailwindcss/vite": ^4.1.18
  "@tsconfig/node22": ^22.0.5
  "@types/bun": ^1.3.5
  "@types/luxon": ^3.7.1
  "@types/node": ^22.0.0
  "@typescript/native-preview": ^7.0.0-dev.20260112.1
  diff: ^8.0.3
  fuzzysort: ^3.1.0
  luxon: ^3.7.2
  marked: ^17.0.1
  marked-shiki: ^1.2.1
  remeda: ^2.33.1
  shiki: ^3.21.0
  solid-js: ^1.9.10
  solid-list: ^0.3.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  virtua: ^0.48.2
  vite: ^7.3.1
  vite-plugin-solid: ^2.11.10
  zod: ^4.3.5
