import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { formatdate, formatpaper, type AnalyzedPaper } from "@/lib/fmt";
import { type Track, TRACKS } from "@/lib/criteria";

const __dirname = dirname(fileURLToPath(import.meta.url));
const RESEARCH_DIR = join(__dirname, "../research");

export interface WriteOptions {
  date?: Date;
  track: Track;
  totalScanned: number;
}

export function write(papers: AnalyzedPaper[], options: WriteOptions): string {
  const { date = new Date(), track, totalScanned } = options;
  const trackInfo = TRACKS[track];
  const dateStr = formatdate(date);
  const filename = `${dateStr}.md`;
  const trackDir = join(RESEARCH_DIR, track);
  const filepath = join(trackDir, filename);

  if (!existsSync(trackDir)) {
    mkdirSync(trackDir, { recursive: true });
  }

  const paperSections = papers.map(formatpaper).join("\n\n---\n\n");
  const categories = trackInfo.categories.join(", ");

  const content = `# arXiv Scout: ${dateStr} — ${trackInfo.name}

Scanned **${totalScanned}** papers from ${categories}.
Found **${papers.length}** relevant.

---

${papers.length > 0 ? paperSections : "_No relevant papers found today._"}

---

*Generated by [arxiv-scout](../../README.md)*
`;

  writeFileSync(filepath, content, "utf-8");
  return filepath;
}
