/**
 * Wakeup types.
 * /packages/kernl/src/wakeup/types.ts
 */

export interface NewScheduledWakeup {
  /**
   * Unique wakeup ID (e.g. ulid/uuid). Generated by Kernl, not by the agent.
   */
  id: string;

  /**
   * Thread to resume when the wakeup becomes due.
   */
  threadId: string;

  /**
   * Duration to sleep (seconds). Preferred over `runAt`.
   *
   * The system will calculate the absolute wakeup time as `created_at + sleepFor`.
   */
  sleepFor?: number;

  /**
   * (Legacy) When this wakeup becomes due (epoch milliseconds).
   *
   * For backward compatibility. Prefer using `sleepFor` instead.
   * Storage providers can store this as seconds (`run_at_s`) or ms,
   * codecs handle conversion.
   */
  runAt?: number;

  /**
   * Optional free-form reason for observability.
   */
  reason?: string | null;
}

/**
 * Persisted wakeup record in domain form.
 */
export interface ScheduledWakeup {
  id: string;
  threadId: string;

  /**
   * Due time in epoch milliseconds (domain-level).
   */
  runAt: number;

  /**
   * Duration to sleep (seconds).
   */
  sleepFor: number;

  reason: string | null;

  /**
   * True once the wakeup has been fully consumed (thread resumed / handled).
   */
  woken: boolean;

  /**
   * When a poller claimed this wakeup (epoch ms). `null` if unclaimed.
   */
  claimedAt: number | null;

  /**
   * Creation and update timestamps (epoch ms).
   */
  createdAt: number;
  updatedAt: number;

  /**
   * Optional error message if processing/resume failed.
   */
  error: string | null;
}

/**
 * Patch payload for updating a wakeup.
 */
export interface ScheduledWakeupUpdate {
  id: string;

  runAt?: number;
  reason?: string | null;

  woken?: boolean;
  claimedAt?: number | null;
  error?: string | null;

  /**
   * Optional explicit updatedAt (ms). Most PG logic will just set
   * this to `Date.now()` if omitted.
   */
  updatedAt?: number;
}
